name: Deploy to Production

on:
  push:
    branches:
      - release

jobs:
  deploy-production:
    environment: 'production'
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: ‚éî Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.13.0'
          registry-url: 'https://registry.npmjs.org'
          scope: '@leapwallet'
      - name: üì• Install Deps
        run: yarn install
      - name: üèóÔ∏è Build
        run: yarn build
      - name: Deploy ‚úàÔ∏è
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: leap-near-sdk-example
          target: production
          channelId: live